import { quoteTotals } from "./quote.js";

function escapeXml(value) {
  const text = String(value ?? "");
  if (/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(text)) throw new Error("HWPX XML cannot contain invalid XML 1.0 characters.");
  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");
}

const crcTable = Array.from({ length: 256 }, (_, n) => { let c = n; for (let i = 0; i < 8; i++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 8; return c >>> 0; });
function crc32(data) { let crc = 0xffffffff; for (const byte of data) crc = crcTable[(crc ^ byte) & 255] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; }
function zip(entries) {
  const local = [], central = []; let offset = 0;
  for (const [name, value] of entries) {
    const nameData = Buffer.from(name), data = Buffer.from(value), crc = crc32(data), flags = name === "mimetype" ? 0 : 0x800;
    const head = Buffer.alloc(30); head.writeUInt32LE(0x04034b50, 0); head.writeUInt16LE(20, 4); head.writeUInt16LE(flags, 6); head.writeUInt32LE(crc, 14); head.writeUInt32LE(data.length, 18); head.writeUInt32LE(data.length, 22); head.writeUInt16LE(nameData.length, 26);
    local.push(head, nameData, data);
    const dir = Buffer.alloc(46); dir.writeUInt32LE(0x02014b50, 0); dir.writeUInt16LE(20, 4); dir.writeUInt16LE(20, 6); dir.writeUInt16LE(flags, 8); dir.writeUInt32LE(crc, 16); dir.writeUInt32LE(data.length, 20); dir.writeUInt32LE(data.length, 24); dir.writeUInt16LE(nameData.length, 28); dir.writeUInt32LE(offset, 42);
    central.push(dir, nameData); offset += head.length + nameData.length + data.length;
  }
  const size = central.reduce((sum, part) => sum + part.length, 0), end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(size, 12); end.writeUInt32LE(offset, 16);
  return Buffer.concat([...local, ...central, end]);
}

let paragraphId = 2;
function paragraph(text) { return `<hp:p id="${paragraphId++}" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="0"><hp:t>${escapeXml(text)}</hp:t></hp:run></hp:p>`; }
function table(rows, widths) {
  const total = widths.reduce((sum, width) => sum + width, 0);
  const cells = rows.map((row, y) => `<hp:tr>${row.map((text, x) => `<hp:tc><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0">${paragraph(text)}</hp:subList><hp:cellAddr colAddr="${x}" rowAddr="${y}"/><hp:cellSpan colSpan="1" rowSpan="1"/><hp:cellSz width="${widths[x]}" height="900"/><hp:cellMargin left="80" right="80" top="40" bottom="40"/><hp:cellProtect locked="0" hidden="0"/></hp:tc>`).join("")}</hp:tr>`).join("");
  return `<hp:p id="${paragraphId++}" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="0"><hp:tbl id="" zOrder="0" numberingType="TABLE" textWrap="TOP_AND_BOTTOM" textFlow="BOTH_SIDES" lock="0" dropcapstyle="None" pageBreak="CELL" repeatHeader="1" rowCnt="${rows.length}" colCnt="${widths.length}" cellSpacing="0" borderFillIDRef="1"><hp:sz width="${total}" widthRelTo="ABSOLUTE" height="${rows.length * 950}" heightRelTo="ABSOLUTE" protect="0"/><hp:pos treatAsChar="1" affectLSpacing="0" flowWithText="1" allowOverlap="0" holdAnchorAndSO="0" vertRelTo="PARA" horzRelTo="COLUMN" vertAlign="TOP" horzAlign="LEFT" vertOffset="0" horzOffset="0"/><hp:outMargin left="0" right="0" top="80" bottom="80"/><hp:inMargin left="0" right="0" top="0" bottom="0"/>${cells}</hp:tbl></hp:run></hp:p>`;
}

export function createHwpx(quote) {
  paragraphId = 2;
  const totals = quoteTotals(quote), money = value => `${Math.round(value).toLocaleString("ko-KR")}원`;
  const items = quote.items.map((item, i) => [String(i + 1), item.name, item.spec || "-", `${item.quantity} ${item.unit}`, money(item.unitPrice), money(item.quantity * item.unitPrice)]);
  while (items.length < 10) items.push([String(items.length + 1), "", "", "", "", ""]);
  const section = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><hs:sec xmlns:hs="http://www.hancom.co.kr/hwpml/2011/section" xmlns:hp="http://www.hancom.co.kr/hwpml/2011/paragraph"><hp:p id="1" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="0"><hp:secPr id="" textDirection="HORIZONTAL" spaceColumns="1134" tabStop="8000" tabStopVal="4000" tabStopUnit="HWPUNIT" outlineShapeIDRef="0" memoShapeIDRef="0" textVerticalWidthHead="0" masterPageCnt="0"><hp:grid lineGrid="0" charGrid="0" wonggojiFormat="0"/><hp:startNum pageStartsOn="BOTH" page="1" pic="1" tbl="1" equation="1"/><hp:visibility hideFirstHeader="0" hideFirstFooter="0" hideFirstMasterPage="0" border="SHOW_ALL" fill="SHOW_ALL" hideFirstPageNum="0" hideFirstEmptyLine="0" showLineNumber="0"/><hp:pagePr landscape="WIDELY" width="59528" height="84186" gutterType="LEFT_ONLY"><hp:margin header="4252" footer="4252" gutter="0" left="5668" right="5668" top="4252" bottom="4252"/></hp:pagePr></hp:secPr></hp:run></hp:p>${table([["Preliminary Pricing", "Quote No.", quote.quoteNumber], ["", "Date", quote.quoteDate], ["", "Valid till", quote.validUntil || "-"]], [25000, 9000, 14000])}${table([["To", "From"], ["Company Name", quote.clientName], ["Contact", quote.clientContact || "-"], ["Address", "-"], ["Company", quote.supplier.companyName || "-"], ["Representative", quote.supplier.representative || "-"], ["Registration", quote.supplier.registrationNumber || "-"], ["Address", quote.supplier.address || "-"]], [12000, 36000])}${table([["Product", quote.items[0]?.name || "-"]], [12000, 36000])}${table([["Quote"], ["No.", "Item", "Spec", "Quantity", "Unit price", "Amount"], ...items, ["", "", "", "", "Total", money(totals.total)]], [3500, 12000, 8500, 7000, 8000, 10000])}${table([["Development"], ["No.", "Content", "Spec", "Cost", "ETC"], ["1", "", "", "", ""], ["2", "", "", "", ""], ["3", "", "", "", ""]], [3500, 12500, 9000, 8000, 16000])}${table([["ETC"], [quote.notes || "-"]], [49000])}${paragraph("1. 견적 내용은 세부 협의에 따라 변경될 수 있습니다.")}${paragraph("2. 금액은 부가세 포함 기준입니다.")}</hs:sec>`;
  const header = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><hh:head xmlns:hh="http://www.hancom.co.kr/hwpml/2011/head" version="1.4" secCnt="1"><hh:beginNum page="1" footnote="1" endnote="1" pic="1" tbl="1" equation="1"/><hh:refList><hh:fontfaces itemCnt="1"><hh:fontface lang="HANGUL" fontCnt="1"><hh:font id="0" face="Pretendard" type="TTF" isEmbedded="0"/></hh:fontface></hh:fontfaces><hh:charProperties itemCnt="1"><hh:charPr id="0" height="900" textColor="#171A20" shadeColor="none" useFontSpace="0" useKerning="0" symMark="NONE" borderFillIDRef="0"><hh:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/><hh:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/><hh:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/><hh:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/><hh:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/></hh:charPr></hh:charProperties><hh:paraProperties itemCnt="1"><hh:paraPr id="0" tabPrIDRef="0" condense="0" fontLineHeight="0" snapToGrid="1" suppressLineNumbers="0" checked="0"><hh:align horizontal="LEFT" vertical="BASELINE"/></hh:paraPr></hh:paraProperties><hh:borderFills itemCnt="2"><hh:borderFill id="0" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:leftBorder type="NONE" width="0.1 mm" color="#000000"/><hh:rightBorder type="NONE" width="0.1 mm" color="#000000"/><hh:topBorder type="NONE" width="0.1 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.1 mm" color="#000000"/><hh:diagonal type="NONE" width="0.1 mm" color="#000000"/><hh:fillBrush><hc:winBrush xmlns:hc="http://www.hancom.co.kr/hwpml/2011/core" faceColor="none" hatchColor="none" alpha="0"/></hh:fillBrush></hh:borderFill><hh:borderFill id="1" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:leftBorder type="SOLID" width="0.12 mm" color="#3E6AE1"/><hh:rightBorder type="SOLID" width="0.12 mm" color="#3E6AE1"/><hh:topBorder type="SOLID" width="0.12 mm" color="#3E6AE1"/><hh:bottomBorder type="SOLID" width="0.12 mm" color="#3E6AE1"/><hh:diagonal type="NONE" width="0.1 mm" color="#000000"/><hh:fillBrush><hc:winBrush xmlns:hc="http://www.hancom.co.kr/hwpml/2011/core" faceColor="#FFFFFF" hatchColor="none" alpha="0"/></hh:fillBrush></hh:borderFill></hh:borderFills><hh:styles itemCnt="1"><hh:style id="0" type="PARA" name="기본 글꼴" engName="Normal" paraPrIDRef="0" charPrIDRef="0" nextStyleIDRef="0" langID="1042" lockForm="0"/></hh:styles></hh:refList></hh:head>`;
  const manifest = `<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/hwp+zip"/><manifest:file-entry manifest:full-path="version.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="settings.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="Contents/content.hpf" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="Contents/header.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="Contents/section0.xml" manifest:media-type="text/xml"/></manifest:manifest>`;
  return zip([["mimetype", "application/hwp+zip"], ["version.xml", `<?xml version="1.0" encoding="UTF-8"?><hv:HCFVersion xmlns:hv="http://www.hancom.co.kr/hwpml/2011/version" targetApplication="WORDPROCESSOR" major="5" minor="1" micro="0" buildNumber="0" os="1" xmlVersion="1.4" application="Quote Maker" appVersion="0.1"/>`], ["META-INF/manifest.xml", manifest], ["META-INF/container.xml", `<?xml version="1.0" encoding="UTF-8"?><container xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="Contents/content.hpf" media-type="application/hwpml-package+xml"/></rootfiles></container>`], ["Contents/content.hpf", `<?xml version="1.0" encoding="UTF-8"?><opf:package xmlns:opf="http://www.idpf.org/2007/opf/" version="3.0"><opf:manifest><opf:item id="header" href="header.xml" media-type="application/xml"/><opf:item id="section0" href="section0.xml" media-type="application/xml"/></opf:manifest><opf:spine><opf:itemref idref="section0" linear="yes"/></opf:spine></opf:package>`], ["Contents/header.xml", header], ["settings.xml", `<?xml version="1.0" encoding="UTF-8"?><ha:HWPApplicationSetting xmlns:ha="http://www.hancom.co.kr/hwpml/2011/app"><ha:CaretPosition listIDRef="0" paraIDRef="1" pos="0"/></ha:HWPApplicationSetting>`], ["Contents/section0.xml", section]]);
}
